import Head from 'next/head'
import React from "react";
import styles from '@/styles/Home.module.css'





export default function Home() {


  return (
    <>
      <Head>
        <title>Authentication-firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
        <h1 className="text-3xl font-bold">
      Hello Wolf! <br/>
      Please Login or Register
    </h1>
        </>
      </main>

    </>
  )
}
